language: python
dist: bionic

notifications:
  slack: yyynazwateamu:pr7HnoeMzkeqiv6bDNGy0rpX

python:
    - "3.7"
services:
  - docker

install:
  - cat requirements.txt

before_script: pip install docker-compose

script:
  - sudo docker-compose run web bash -c "pytest"