# Generated by Django 2.2.5 on 2019-09-14 22:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[accounts.models.validate_ticket_number]),
        ),
    ]
