# Generated by Django 2.2.5 on 2019-09-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
