version: '3'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: bash -c "npm run build"

volumes:
  web-static:
  pgdata:
#  redisdata: