# Generated by Django 2.2.5 on 2019-09-14 21:05

from django.db import migrations, models
import train.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('IC', 'ic'), ('TLK', 'tlk')], max_length=3)),
                ('departure_time', models.DateTimeField(default=train.models.get_train_departure_time)),
                ('departure_city', models.CharField(max_length=20)),
                ('arrival_city', models.CharField(max_length=20)),
            ],
        ),
    ]
